---
- name: Playbook - Install figlet
  hosts: planetexpress
  gather_facts: yes   # default is yes

  tasks:
  - name: using apt to install figlet
    package:
        name: figlet
        state: present
    become: yes

