---
- name: A simple playbook to test ansible.cfg
  hosts: planetexpress
  gather_facts: yes
  gather_subset: network
  connection: ssh

  tasks:

  - name: Issue a date cmd on each remote host
    command: date

